// <auto-generated />
namespace VideoShopApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class applyconstraintsannotationstocustomername : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(applyconstraintsannotationstocustomername));
        
        string IMigrationMetadata.Id
        {
            get { return "202005251250554_applyconstraints/annotations to customer name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
